auto: true
markdown: rdiscount
permalink: /:year/:month/:day/:title
rdiscount extensions: [smart]
exclude:
  - '*.sh'
  - '*.txt'
  - '*.py'
  - '*.log'
  - 'Makefile'
  - 'README.md'
  - 'TODO.md'
  - 'exclude/'
collections:
  fun:
    output: true
  projects:
